export const VITE_FIREBASE_API_KEY = import.meta.env.VITE_FIREBASE_API_KEY;
export const VITE_FIREBASE_AUTH_DOMAIN = import.meta.env
    .VITE_FIREBASE_AUTH_DOMAIN;
export const VITE_FIREBASE_PROJECTID = import.meta.env.VITE_FIREBASE_PROJECTID;
export const VITE_FIREBASE_STORAGE_BUCKET = import.meta.env
    .VITE_FIREBASE_STORAGE_BUCKET;
export const VITE_FIREBASE_MESSAGING_SENDERID = import.meta.env
    .VITE_FIREBASE_MESSAGING_SENDERID;
export const VITE_FIREBASE_APPID = import.meta.env.VITE_FIREBASE_APPID;
export const VITE_FIREBASE_MEASUREMENTID = import.meta.env
    .VITE_FIREBASE_MEASUREMENTID;
